server:
  port: 8080
  cors:
    allowOrigins:
      - http://localhost:5173
    allowCredentials: true
    maxAge: 24
    allowMethods:
      - GET
      - POST
      - DELETE
      - OPTIONS
      - HEAD

database:
  host: localhost
  port: 5432
  username: ${DB_USER}
  password: ${DB_PASSWORD}
  db: auth-service-go
  sslmode: disable
  time_zone: UTC

jwt:
  expiry_minutes: 15
  jwt_secret: ${JWT_SECRET}
  refresh_token_expiry_hours: 2
