server:
  port: 8080

database:
  host: localhost
  port: 5432
  username: ${DB_USER}
  password: ${DB_PASSWORD}
  db: auth-service-go
  sslmode: disable
  time_zone: UTC

jwt:
  expiry_hours: 72
  jwt_secret: ${JWT_SECRET}
